---
output: html_document
---

<br>
<br>


## Education

---


Ph.D in Geography - University of North Carolina at Greensboro, Greensboro, NC -Expected Graduation: 2022 <br>
MS in Geography - Western Michigan University, Kalamazoo, MI - 2019 <br>
MS in Biology - Grand Valley State University, Allandale, MI - 2017 <br>
Bsc. in Environmental Science - Tribhuvan University, Kathmandu, Nepal - 2014

\


## Honors and Awards

---

Graduate Dean Citation of Academic Excellence (2017) by Grand Valley State University: For Excellence in Service to the Community or Profession
  
Graduate Research and Creative Scholar Award (2019) by Department of Geography, Environment, and Tourism of Western Michigan University: For outstanding contribution to the field of GIS 
  
2nd Place Winner in 3 Minute Thesis Competition (2019): Western Michigan University: Presented objectives, methods, results, and conclusion of the research within 3 minutes 

1st Place Winner in Great Lakes AAG Masters Degree Student Research Competition: Presented objectives, methods, results, and conclusion of the research within 20 minutes
   
---

\


This video was taken by Graduate Student Association of Western Michigan University during 3MT competition. I was awarded with second prize in the competition. Kindly note that I have improved my accent since then `r emo::ji("smile")` 

\


<style type="text/css">
.responsive {
  width: 100%;
  height: 0;
  padding-bottom: 56.25%;
  position: relative;

}
.responsive iframe {
  position: absolute;
  width: 80%;
  height: 80%;
}

</style>

<div class="responsive">
   <iframe width="400" height="300" src="https://www.youtube.com/embed/eomfFC7JtsQ" frameborder="0" allowfullscreen></iframe>  
   Click play button to watch the video
</div>

---
