---
title: "Education and Awards"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    df_print: paged
---

### Education


* Ph.D in Geography - University of North Carolina at Greensboro, Greensboro, NC -Expected Graduation: 2022
* MS in Geography - Western Michigan University, Kalamazoo, MI - 2019
* MS in Biology - Grand Valley State University, Allandale, MI - 2017
* Bsc. in Environmental Science - Tribhuvan University, Kathmandu, Nepal - 2014

### Honors and Awards

* Graduate Dean Citation of Academic Excellence (2017): Grand Valley State University
  + This award is given for Excellence in Service to the Community or Profession
  
* Graduate Research and Creative Scholar Award (2019): Department of Geography, Environment, and Toursim of Western Michigan University
  + For outstanding contribution to the field of GIS. 
  
* 2nd Place Winner in 3 Minute Thesis Competition (2019): Western Michigan University 
   + Presented objectives, methods, results, and conclusion of the research within 3 minutes. 

<style type="text/css">
.responsive {
  width: 100%;
  height: 0;
  padding-bottom: 56.25%;
  position: relative;

}
.responsive iframe {
  position: absolute;
  width: 100%;
  height: 100%;
}

</style>


* 1st Place Winner in Great Lakes AAG Masters Degree Student Research Competition 
   + Presented objectives, methods, results, and conclusion of the research within 20 minutes.
   
<br>
<br>
<br>
<br>
<br>

<div class="responsive">
   <iframe width="400" height="300" src="https://www.youtube.com/embed/eomfFC7JtsQ" frameborder="0" allowfullscreen></iframe>  
   Click play button to watch the video
</div>
