---
output: html_document
---

\

<style type="text/css">
body {
  font-size: 12pt;
}

h1, h2, h3{
  color: #4682B4;
}

#TOC {
  margin: 25px 0px 20px 0px;
}

hr {
  border-top: 5px solid #F0F8FF;
}

.clearfix {
  overflow: auto;
}

img {
  margin-right: 20px;
  box-shadow: 5px 5px 10px #ccc;
}

</style>


*Do you want to learn how to code in R?* Here are some of the tutorials that you can follow step by step to help you in your journey of learning R. 

\

## Analysis of Pilot Study Data

---

This publication features an analysis of data collected during a pilot study of dead large wood at Greensboro's North Buffalo Creek. [Click here](https://rpubs.com/rajesh1/701224){target="_blank} to download the data and to learn how to clean, manipulate, and reshape data using various packages in R. In this article, you will also learn how to make histograms, box and whisker plot, how to join tables, and how to conduct chi-square tests, and Kruskal Wallis tests.

\

## Elevation Range of species

---

Have you every wondered how to create Gantt Chart in R that shows the elevational range of different species? [Click here](https://rpubs.com/rajesh1/elevationGraph){target="_blank} to learn more about how to convert sparse matrix into tidy format and create Gantt Chart in R. 

\


## Understanding Correlation

---

In this tutorial, I have exlained the different types of Correlation and how to compute them in R. [Click here](https://rpubs.com/rajesh1/563805){target="_blank} to learn more about it.

\


## Bar Graph, Cluster Analyiss, and Hexbin Map

---

In this tutorial, you can learn about how to make Bar Graph, and how to compute cluster Analysis. You will also learn how to make a Hexbin map using GeoJason data.  [Click here](https://rpubs.com/rajesh1/610825){target="_blank}
\
\